name: Build

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build_Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure and Build Windows
        run: | 
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload artifacts Windows
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows
          path: |
            build/bin/Release/rtt-server.exe
            build/bin/Release/rtt-client.exe
            build/bin/Release/udp-profile.exe

      - name: Release Windows
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/Release/*.exe

  build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update and Install dependencies
        run: | 
          sudo apt update
          sudo apt upgrade 

      - name: Configure and Build Linux
        run: | 
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      
      - name: Upload artifacts Linux
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux
          path: |
            build/bin/rtt-server
            build/bin/rtt-client
            build/bin/udp-profile

      - name: Release Linux
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/rtt-server
            build/bin/rtt-client
            build/bin/udp-profile
